version: 0.1
os: linux

hooks:
  BeforeInstall:
    - location: ./scripts/stop_app1.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_app1.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./scripts/start_app.sh
      timeoout: 300
      runas: root
